//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SpeechStrings
{
	public const string ANX_LIGHT = "I'm anxious about the light switch";
	public const string ANX_LIGHT_DONE = "OK!";

	public const string ANX_CLEAN = "I want to wash my hands";
	public const string ANX_CLEAN_DONE = "Yay, clean hands";

	public const string ANX_SECURITY = "Am I safe?";
	public const string ANX_SECURITY_DONE = "I think I'm safe";

	// Haven't name anything else yet - add strings for the other proposed types
	// with const names based on above I guess
}


